services:
  db:
    image: postgres:17
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    build:
      context: ./phishing_detector
    container_name: django_backend
    command: gunicorn --bind 0.0.0.0:8000 phishing_detector.wsgi:application
    volumes:
      - ./phishing_detector:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000 # เปิดให้แค่ใน network Docker เห็น
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./phishing-detector-frontend
      dockerfile: Dockerfile.prod
    container_name: react_frontend
    # ไม่ต้อง map port ออกข้างนอกแล้ว เพราะจะผ่าน nginx proxy

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    ports:
      - "80:80" # service เดียวที่จะเปิด port สู่ภายนอก
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume: