# Generated by Django 4.2.7 on 2025-08-17 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('risk_score', models.FloatField()),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TB_EmailAnalysis',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('reliability', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TB_SystemEvaluation',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.TextField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.emailanalysis')),
            ],
            options={
                'db_table': 'TB_Report',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TB_Admin',
            },
        ),
    ]
